In [ ]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [1]:
import numpy as np

# Create a 2x3 numpy array with all elements as 5
arr = np.full((2, 3), 5)

# Print the array
print(arr)


[[5 5 5]
 [5 5 5]]


**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [2]:
import numpy as np

# Create a 2x3 numpy array with random values
rand_arr = np.random.rand(2, 3)

# Print the array
print(rand_arr)


[[0.59176384 0.48546422 0.92789494]
 [0.81622349 0.01525725 0.2676446 ]]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value

In [3]:
import numpy as np

# Assuming rand_arr is already defined as a 2x3 array with random values
# rand_arr = np.random.rand(2, 3)

# Calculate the sum of all elements in the array
arr_sum = np.sum(rand_arr)

# Calculate the mean of the elements in the array
arr_mean = np.mean(rand_arr)

# Find the maximum value among the elements in the array
arr_max = np.max(rand_arr)

# Find the minimum value among the elements in the array
arr_min = np.min(rand_arr)

# Print the results
print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')


sum: 3.1042483431781687
mean: 0.5173747238630281
max: 0.9278949416030023
min:0.015257250456978122


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [4]:
import numpy as np

# Define an array
arr = np.array([[5, 12, 51, 25], [25, 29, 2, 27]])
print(f'Array:\n{arr}\n')

# Find the position of maximum and minimum value of the array
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print(f'Max Index: {max_idx}, Min Index: {min_idx}')

# Find the indices of maximum and minimum value along each of its columns
max_col = np.argmax(arr, axis=0)
min_col = np.argmin(arr, axis=0)
print(f'Max Indices per Column: {max_col}, Min Indices per Column: {min_col}')

# Find the indices of maximum and minimum value along each of its rows
max_row = np.argmax(arr, axis=1)
min_row = np.argmin(arr, axis=1)
print(f'Max Indices per Row: {max_row}, Min Indices per Row: {min_row}')


Array:
[[ 5 12 51 25]
 [25 29  2 27]]

Max Index: 2, Min Index: 6
Max Indices per Column: [1 1 0 1], Min Indices per Column: [0 0 1 0]
Max Indices per Row: [2 1], Min Indices per Row: [0 2]
